name: big_ticket1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.1
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  #flutter_native_splash: ^2.2.19
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  barcode_image: ^2.0.2
  csv: ^5.0.1
  #flutter_native_splash: ^2.2.9
  signature: ^5.2.1
  pdf:
  open_file: ^3.2.1
  open_document: ^1.0.4
  syncfusion_flutter_pdf: ^21.1.39
  #image: ^4.0.15
  barcode_widget: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/HomecomingReport1.csv
    - assets/HomecomingTicketReport2.csv
